### ISSUE TITLE
Should we partial word match?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/search-result-keyword-highlighter#7]
If a person searches for `Java` and the `text` contains `JavaScript` should that be a match...?

thoughts...?

**Comment by iteles** [comment]
Good question. I personally would find this annoying because if I'm searching for something I don't want to see irrelevant information.  

But some audiences might be interested in this, for example if I'm a community manager and I deal with a _lot_ of people on a daily basis, I might roughly know someone's name but not entirely, so if I type in `Jam` it might also be useful for the `Jam` portion of `James`, `Jameel` and `Jameson` came up in my results so I could quickly look through all the other information on the page and find what's useful.

Would be interested in knowing other people's thoughts!

**Comment by nelsonic** [comment]
We should get the _customer_'s feedback once we ship this feature. :+1:

**Comment by nelsonic** [comment]
The _beauty_ is that ElasticSearch will only match complete words or _stems_ but not incomplete.
so the search for `Jam` will not return `James` in the first place.
This `highlighter` is going to work **_client**_-_side_ so it highlights after the page has loaded.
Thus not impacting page-load time for search results.
